String teachername="Tess Løvgreen";
int daysinyear=365;
String city="København";
boolean isteacher=true;
int minutesinday=60*24;
int timeofday=22.12
String greeting="Hej, jeg heddder "+teachername;
boolean isstudent=false;
double equation=2.2 + 33;
char letter='S';
